### PR TITLE
add documentation for questionnaire_template_api

### PR DESCRIPTION
**Pull request by ionut998**

### CODE REVIEW

**Comment by jonnyarnold** [comment]
LGTM

**Comment by jonnyarnold** [comment]
On hold - discussing how to publicise this API.

**Comment by lpil** [comment]
What's going on here @jonnyarnold @ionut998 ?

**Comment by reneklacan** [comment]
What's going on here @lpil @jonnyarnold @ionut998 ?

**Comment by jonnyarnold** [comment]
I'm pretty sure we still don't want to publicise the Questionnaire API yet. Ask @ionut998 when he gets back from holiday.

**Comment by lpil** [comment]
Can we just close this then?

**Comment by jonnyarnold** [comment]
Closed but not deleted.

**Pull request closed without merging**
