### PR TITLE
Move Maciej to the alumni list

### PR DESCRIPTION
**Pull request by Sodki**

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
*If you're new, read the [guidelines]
(https://github.com/reevoo/guidelines/blob/master/pull_requests.md).*

Good code is **tested**, **designed for change**, **easy to understand**
and **able to cope when things go wrong**.

Good pull requests are **descriptive**, **small** and **short-lived**.

**For the Author**
- [ ] Description explains what you have done and why.
- [ ] Tests have been written (or you have explained why you don't need
tests).
- [ ] Documentation/comments have been added/updated.

**For the Reviewer**
- [ ] The code is well-designed and able to cope with change.
- [ ] The code is easy to understand.
- [ ] Tests cover happy and unhappy paths in the code.
- [ ] Tests are green on CI (or pulled/tested on your machine).

**Comment by Sodki** [comment]
I have no URL for Maciej's picture. If you feel it should have one, can you provide it? Thanks.

**Comment by leahyc** [comment]
No need for the URL I reckon - I doubt he has one. Gustavo, Mike Krzywinski
and Naomi need moving to the traitor list as well... ;-)

On Thu, Jun 16, 2016 at 11:05 AM, Henrique Rodrigues <
notifications@github.com> wrote:

> I have no URL for Maciej's picture. If you feel it should have one, can
> you provide it? Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/reevoo/reevoo.github.io/pull/98#issuecomment-226442934>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjDBUUdDa-XfhAblkpb7LmwJviQmLICks5qMR_lgaJpZM4I3OaB>
> .
>



-- 

Cian Leahy
Head of QA

E: cian.leahy@reevoo.com
A: 41-45 Blackfriars Road, London SE1 8NZ

[image: Reevoo] <https://www.reevoo.com/>
<https://www.reevoo.com/>

<https://www.reevoo.com/>[image: Reevoo] [image: Twitter]
<https://twitter.com/reevoo> [image: Facebook]
<https://www.facebook.com/reevoo> [image: LinkedIn]
<https://www.linkedin.com/company/reevoo> [image: LinkedIn]
<https://blog.reevoo.com/>

*This is one of those messages we need to put at the bottom of emails
telling people that this message and any attachments are confidential, and
only for the eyes of the intended recipient (obviously). If you don't think
it's for you, please delete it and let the sender know. And don't talk to
strangers.*

**Comment by Sodki** [comment]
I've alumnised the rest of the alumnis.

**Comment by shyvy88** [comment]
@leahyc I can see your blasphemous speech. Don't think we don't see.

**Comment by leahyc** [comment]
I recommend removing all traces of Mike K - he shall be stricken from the
record...

On Fri, Jun 17, 2016 at 2:33 PM, Michal Krzywinski <notifications@github.com
> wrote:

> @leahyc <https://github.com/leahyc> I can see your blasphemous speech.
> Don't think we don't see.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/reevoo/reevoo.github.io/pull/98#issuecomment-226769777>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjDBVBB2Ocl807dPXpxT6udNpShSOMyks5qMqI6gaJpZM4I3OaB>
> .
>



-- 

Cian Leahy
Head of QA

E: cian.leahy@reevoo.com
A: 41-45 Blackfriars Road, London SE1 8NZ

[image: Reevoo] <https://www.reevoo.com/>
<https://www.reevoo.com/>

<https://www.reevoo.com/>[image: Reevoo] [image: Twitter]
<https://twitter.com/reevoo> [image: Facebook]
<https://www.facebook.com/reevoo> [image: LinkedIn]
<https://www.linkedin.com/company/reevoo> [image: LinkedIn]
<https://blog.reevoo.com/>

*This is one of those messages we need to put at the bottom of emails
telling people that this message and any attachments are confidential, and
only for the eyes of the intended recipient (obviously). If you don't think
it's for you, please delete it and let the sender know. And don't talk to
strangers.*

**Comment by shyvy88** [comment]
Why perpetuate hate @leahyc? You're better than that.

**Comment by seddy** [comment]
Don't worry @leahyc, I've already modified @shyvy88's author name from `Michal Kryzwinski` to his more well known colloquial name (i.e. the opposite of "Nice Mike") in all commits to reevoo repos :)

**Pull request merged**
