### PR TITLE
Your Code as a Crime Scene

### PR DESCRIPTION
**Pull request by jonnyarnold**
Also features some CSS changes to make tables look not crap. :boom:

### CODE REVIEW

**Comment by lpil** [comment]
The mobile layout is kinda broken thanks to the tables. How about we wrap it in a div that is fixed to the width of the viewport and then has `overflow: auto` so it scrolls horizontally inside just that one element?

**Comment by lpil** [comment]
Mobile layout footer is broken too, though that's also the case on master it seems...

**Comment by jonnyarnold** [comment]
Sad times for Markdown tables that don't work.

**Comment by jonnyarnold** [comment]
Thanks @lpil!

**Comment by lpil** [comment]
:dancer:

**Pull request merged**
