### PR TITLE
New post guide

### PR DESCRIPTION
**Pull request by lpil**
How does this look @ZoeFeltham ? :) https://github.com/reevoo/reevoo.github.io/blob/guide/README.md

### CODE REVIEW

**Comment by errm** [comment]
Do we need some instructions on pulling changes from upstream into a fork?  
Or should we recommend deleting the fork after someone has written a post?

Or would it be simpler to add people as collaborators to this repo and get them to push to a branch?

**Comment by lpil** [comment]
> Do we need some instructions on pulling changes from upstream into a fork?

Probably, but this is kinda complex, and I wasn't sure how to put this into words in a friendly fashion. I threw what we have so far at Jayson and Zoe and I don't think even this was clear enough. Might be easier to just have them email me a blog and I'll put it up.

> Or should we recommend deleting the fork after someone has written a post?

Probably easier to do this. This is what I was thinking.

> Or would it be simpler to add people as collaborators to this repo and get them to push to a branch?

I didn't want to do this because pushing to master accidentally would be easy.

**Comment by errm** [comment]
This looks somewhat interesting https://github.com/alagu/pagoda, perhaps we could make something with that and have an editor running localy

**Comment by lpil** [comment]
With the current rate of blog posts it'd be easier just to get people to email them to me.

**Comment by errm** [comment]
Or open issues on the repo with the text?

**Pull request merged**
